Testing comment creation and conditions

diff --git a/.github/workflows/branch-name-policy.yml b/.github/workflows/branch-name-policy.yml
--- a/.github/workflows/branch-name-policy.yml
+++ b/.github/workflows/branch-name-policy.yml
@@ -25,17 +25,21 @@ jobs:
 
       # Runs a single command using the runners shell
       - name: Run a one-line script
-        run: echo Hello, world!
-
-      # Runs a set of commands using the runners shell
-      - name: Post branch name warning comment
         uses: zendesk/github-script@v1
         with:
           github-token: ${{secrets.GITHUB_TOKEN}}
           script: |
-            branch_name=$(echo "${GITHUB_HEAD_REF:-$GITHUB_REF}" | sed -e 's/refs\/heads\///')
-            branch_name_length=${#branch_name}
+            github.issues.createComment({
+              issue_number: context.issue.number,
+              owner: context.repo.owner,
+              repo: context.repo.repo,
+              body: 'New comment on git'
+            })
 
-            if [[ $branch_name_length -gt 49 ]]; then
-              echo "Warning: Branch name (${branch_name}) contains more than 49 characters. Deployment is bound to fail for branches with long names" && exit 1
-            fi
+      # Runs a set of commands using the runners shell
+      - if: ${{ branch_name=$(echo "${GITHUB_HEAD_REF:-$GITHUB_REF}" | sed -e 's/refs\/heads\///') && branch_name_length=${#branch_name} && ($branch_name_length -gt 49) }}
+      - name: Post branch name warning comment
+        uses: zendesk/github-script@v1
+        with:
+          script: |
+            echo "Deployment is bound to fail for branches with long names" && exit 1
