Testing comment creation and conditions

diff --git a/.github/workflows/branch-name-policy.yml b/.github/workflows/branch-name-policy.yml
--- a/.github/workflows/branch-name-policy.yml
+++ b/.github/workflows/branch-name-policy.yml
@@ -24,7 +24,7 @@ jobs:
     steps:
 
       # Runs a single command using the runners shell
-      - name: Run a one-line script
+      - name: Post comment
         uses: zendesk/github-script@v1
         with:
           github-token: ${{secrets.GITHUB_TOKEN}}
@@ -37,9 +37,7 @@ jobs:
             })
 
       # Runs a set of commands using the runners shell
-      - if: ${{ branch_name=$(echo "${GITHUB_HEAD_REF:-$GITHUB_REF}" | sed -e 's/refs\/heads\///') && branch_name_length=${#branch_name} && ($branch_name_length -gt 49) }}
       - name: Post branch name warning comment
-        uses: zendesk/github-script@v1
-        with:
-          script: |
-            echo "Deployment is bound to fail for branches with long names" && exit 1
+      - if: ${{ branch_name=$(echo "${GITHUB_HEAD_REF:-$GITHUB_REF}" | sed -e 's/refs\/heads\///') && branch_name_length=${#branch_name} && ($branch_name_length -gt 49) }}
+        run:
+          echo "Deployment is bound to fail for branches with long names" && exit 1
